version: '3'
services:

  postgres:
    image: 'registry.hub.docker.com/library/postgres:9.5.14'
    container_name: postgres
    ports:
    - "5432:5432"
    env_file:
    - ./env.db
    volumes:
    - "postgres-data:/var/lib/postgresql/data:rw"
    #      - ./xmp_metadata.sql:/docker-entrypoint-initdb.d/xmp_metadata.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10

  cassandra:
    image: 'localhost/gms-common/cassandra:latest'
    container_name: cassandra
    ports:
    - "9042:9042"
    volumes:
    - cassandra-data:/var/lib/cassandra
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  osd-waveforms-repository-service:
    image: 'localhost/gms-common/osd-waveforms-repository-service:latest'
    container_name: osd-waveforms-repository-service
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    - cassandra
    environment:
    - persistence_url=jdbc:postgresql://postgres:5432/xmp_metadata
    - cassandra_connect_points=cassandra
    healthcheck:
      test: ["CMD", "curl", "localhost:8080/mechanisms/object-storage-distribution/waveforms/alive"]
      interval: 5s
      timeout: 10s
      retries: 10

  osd-signaldetection-repository-service:
    image: 'localhost/gms-common/osd-signaldetection-repository-service:latest'
    container_name: osd-signaldetection-repository-service
    ports:
    - "8082:8080"
    depends_on:
    - postgres
    - cassandra
    environment:
    - persistence_url=jdbc:postgresql://postgres:5432/xmp_metadata
    - cassandra_connect_points=cassandra
    healthcheck:
      test: ["CMD", "curl", "localhost:8080/mechanisms/object-storage-distribution/signal-detection/alive"]
      interval: 5s
      timeout: 10s
      retries: 10

  beam-control-service:
    #image: 'localhost/gms-common/fk-control-service:${VERSION}'
    build: 'beam-control-service'
    container_name: beam-control-service
    ports:
    - "8084:8080"
#    environment:
#    - signaldetection_persistence_url=jdbc:postgresql://postgres:5432/xmp_metadata
#    - waveform_persistence_url=jdbc:postgresql://postgres:5432/xmp_metadata
#    - fk_persistence_url=jdbc:postgresql://postgres:5432/xmp_metadata
    healthcheck:
      test: ["CMD", "curl", "beam-control-service:8080/signal-enhancement/beam/alive"]
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
    - cassandra
    - postgres

volumes:
  postgres-data:
  cassandra-data:
