package gms.shared.mechanisms.objectstoragedistribution.coi.signaldetection.repository.jpa.utility;

import gms.shared.mechanisms.objectstoragedistribution.coi.common.PhaseType;
import java.util.EnumMap;
import java.util.Map;

public class PhaseTypeConverter extends AttributeToIntegerConverter<PhaseType> {

  private static final Map<PhaseType, Integer> toColumn;

  static {
    toColumn = new EnumMap<>(PhaseType.class);
    toColumn.put(PhaseType.UNKNOWN,  0  );
    toColumn.put(PhaseType.P,        1  );
    toColumn.put(PhaseType.S,        2  );
    toColumn.put(PhaseType.I,        3  );
    toColumn.put(PhaseType.l,        4  );
    toColumn.put(PhaseType.Lg,       5  );
    toColumn.put(PhaseType.LQ,       6  );
    toColumn.put(PhaseType.LR,       7  );
    toColumn.put(PhaseType.nNL,      8  );
    toColumn.put(PhaseType.NP,       9  );
    toColumn.put(PhaseType.NP_1,     10 );
    toColumn.put(PhaseType.P3KP,     11 );
    toColumn.put(PhaseType.P3KPbc,   12 );
    toColumn.put(PhaseType.P3KPbc_B, 13 );
    toColumn.put(PhaseType.P3KPdf,   14 );
    toColumn.put(PhaseType.P3KPdf_B, 15 );
    toColumn.put(PhaseType.P4KP,     16 );
    toColumn.put(PhaseType.P4KPbc,   17 );
    toColumn.put(PhaseType.P4KPdf,   18 );
    toColumn.put(PhaseType.P4KPdf_B, 19 );
    toColumn.put(PhaseType.P5KP,     20 );
    toColumn.put(PhaseType.P5KPbc,   21 );
    toColumn.put(PhaseType.P5KPbc_B, 22 );
    toColumn.put(PhaseType.P5KPdf,   23 );
    toColumn.put(PhaseType.P5KPdf_B, 24 );
    toColumn.put(PhaseType.P5KPdf_C, 25 );
    toColumn.put(PhaseType.P7KP,     26 );
    toColumn.put(PhaseType.P7KPbc,   27 );
    toColumn.put(PhaseType.P7KPbc_B, 28 );
    toColumn.put(PhaseType.P7KPbc_C, 29 );
    toColumn.put(PhaseType.P7KPdf,   30 );
    toColumn.put(PhaseType.P7KPdf_B, 31 );
    toColumn.put(PhaseType.P7KPdf_C, 32 );
    toColumn.put(PhaseType.P7KPdf_D, 33 );
    toColumn.put(PhaseType.Pb,       34 );
    toColumn.put(PhaseType.PcP,      35 );
    toColumn.put(PhaseType.PcS,      36 );
    toColumn.put(PhaseType.Pdiff,    37 );
    toColumn.put(PhaseType.Pg,       38 );
    toColumn.put(PhaseType.PKhKP,    39 );
    toColumn.put(PhaseType.PKiKP,    40 );
    toColumn.put(PhaseType.PKKP,     41 );
    toColumn.put(PhaseType.PKKPab,   42 );
    toColumn.put(PhaseType.PKKPbc,   43 );
    toColumn.put(PhaseType.PKKPdf,   44 );
    toColumn.put(PhaseType.PKKS,     45 );
    toColumn.put(PhaseType.PKKSab,   46 );
    toColumn.put(PhaseType.PKKSbc,   47 );
    toColumn.put(PhaseType.PKKSdf,   48 );
    toColumn.put(PhaseType.PKP,      49 );
    toColumn.put(PhaseType.PKP2,     50 );
    toColumn.put(PhaseType.PKP2ab,   51 );
    toColumn.put(PhaseType.PKP2bc,   52 );
    toColumn.put(PhaseType.PKP2df,   53 );
    toColumn.put(PhaseType.PKP3,     54 );
    toColumn.put(PhaseType.PKP3ab,   55 );
    toColumn.put(PhaseType.PKP3bc,   56 );
    toColumn.put(PhaseType.PKP3df,   57 );
    toColumn.put(PhaseType.PKP3df_B, 58 );
    toColumn.put(PhaseType.PKPab,    59 );
    toColumn.put(PhaseType.PKPbc,    60 );
    toColumn.put(PhaseType.PKPdf,    61 );
    toColumn.put(PhaseType.PKPPKP,   62 );
    toColumn.put(PhaseType.PKS,      63 );
    toColumn.put(PhaseType.PKSab,    64 );
    toColumn.put(PhaseType.PKSbc,    65 );
    toColumn.put(PhaseType.PKSdf,    66 );
    toColumn.put(PhaseType.PmP,      67 );
    toColumn.put(PhaseType.Pn,       68 );
    toColumn.put(PhaseType.PnPn,     69 );
    toColumn.put(PhaseType.PP,       70 );
    toColumn.put(PhaseType.PP_1,     71 );
    toColumn.put(PhaseType.PP_B,     72 );
    toColumn.put(PhaseType.pPdiff,   73 );
    toColumn.put(PhaseType.pPKiKP,   74 );
    toColumn.put(PhaseType.pPKP,     75 );
    toColumn.put(PhaseType.pPKPab,   76 );
    toColumn.put(PhaseType.pPKPbc,   77 );
    toColumn.put(PhaseType.pPKPdf,   78 );
    toColumn.put(PhaseType.PPP,      79 );
    toColumn.put(PhaseType.PPP_B,    80 );
    toColumn.put(PhaseType.PPS,      81 );
    toColumn.put(PhaseType.PPS_B,    82 );
    toColumn.put(PhaseType.PS,       83 );
    toColumn.put(PhaseType.PS_1,     84 );
    toColumn.put(PhaseType.pSdiff,   85 );
    toColumn.put(PhaseType.pSKS,     86 );
    toColumn.put(PhaseType.pSKSac,   87 );
    toColumn.put(PhaseType.pSKSdf,   88 );
    toColumn.put(PhaseType.Rg,       89 );
    toColumn.put(PhaseType.Sb,       90 );
    toColumn.put(PhaseType.ScP,      91 );
    toColumn.put(PhaseType.ScS,      92 );
    toColumn.put(PhaseType.Sdiff,    93 );
    toColumn.put(PhaseType.Sg,       94 );
    toColumn.put(PhaseType.SKiKP,    95 );
    toColumn.put(PhaseType.SKKP,     96 );
    toColumn.put(PhaseType.SKKPab,   97 );
    toColumn.put(PhaseType.SKKPbc,   98 );
    toColumn.put(PhaseType.SKKPdf,   99 );
    toColumn.put(PhaseType.SKKS,     100);
    toColumn.put(PhaseType.SKKSac,   101);
    toColumn.put(PhaseType.SKKSac_B, 102);
    toColumn.put(PhaseType.SKKSdf,   103);
    toColumn.put(PhaseType.SKP,      104);
    toColumn.put(PhaseType.SKPab,    105);
    toColumn.put(PhaseType.SKPbc,    106);
    toColumn.put(PhaseType.SKPdf,    107);
    toColumn.put(PhaseType.SKS,      108);
    toColumn.put(PhaseType.SKS2,     109);
    toColumn.put(PhaseType.SKS2ac,   110);
    toColumn.put(PhaseType.SKS2df,   111);
    toColumn.put(PhaseType.SKSac,    112);
    toColumn.put(PhaseType.SKSdf,    113);
    toColumn.put(PhaseType.SKSSKS,   114);
    toColumn.put(PhaseType.Sn,       115);
    toColumn.put(PhaseType.SnSn,     116);
    toColumn.put(PhaseType.SP,       117);
    toColumn.put(PhaseType.SP_1,     118);
    toColumn.put(PhaseType.sPdiff,   119);
    toColumn.put(PhaseType.sPKiKP,   120);
    toColumn.put(PhaseType.sPKP,     121);
    toColumn.put(PhaseType.sPKPab,   122);
    toColumn.put(PhaseType.sPKPbc,   123);
    toColumn.put(PhaseType.sPKPdf,   124);
    toColumn.put(PhaseType.SS,       125);
    toColumn.put(PhaseType.SS_1,     126);
    toColumn.put(PhaseType.SS_B,     127);
    toColumn.put(PhaseType.sSdiff,   128);
    toColumn.put(PhaseType.sSKS,     129);
    toColumn.put(PhaseType.sSKSdf,   130);
    toColumn.put(PhaseType.SSS,      131);
    toColumn.put(PhaseType.SSS_B,    132);
    toColumn.put(PhaseType.T,        133);
  }

  public PhaseTypeConverter() {
    super(toColumn);
  }
}
