version: '3.7'

x-parent-image: &parent_image ${DOCKER_REGISTRY}/${REGISTRY_BASE}/centos7/openjdk8:${TAG}

services:
  wiremock:
    image: ${DOCKER_REGISTRY}/${REGISTRY_BASE}/centos7/openjdk8/wiremock:${TAG}
    build:
      context: ./wiremock
      args:
        FROM_IMAGE: *parent_image
