version: '3.7'

x-parent-image: &parent_image ${DOCKER_REGISTRY}/${REGISTRY_BASE}/centos7/python36/pip:${TAG}

services:
  pybuilder:
    image: ${DOCKER_REGISTRY}/${REGISTRY_BASE}/centos7/python36/pip/pybuilder:${TAG}
    build:
      context: ./pybuilder
      args:
        FROM_IMAGE: *parent_image
