version: '3.7'

x-parent-image: &parent_image ${DOCKER_REGISTRY}/${REGISTRY_BASE}/centos7/openjdk9/gradle4:${TAG}

services:
  integration:
    image: ${DOCKER_REGISTRY}/${REGISTRY_BASE}/centos7/openjdk9/gradle4/integration:${TAG}
    build:
      context: ./integration
      args:
        FROM_IMAGE: *parent_image
