version: '3'
services:

  detector-control:
    image: "${CI_DOCKER_REGISTRY}/beam-control"
    depends_on:
      - detector-osd-gateway
    ports:
      - "8080:8080"
    restart: always
    networks:
      - gms

  detector-osd-gateway:
    image: "${CI_DOCKER_REGISTRY}/beam-osd-gateway"
    depends_on:
      - osd-postgres
    ports:
      - "8081:8080"
    restart: always
    networks:
      - gms

  osd-postgres:
    image: "${CI_DOCKER_REGISTRY}/postgres:9.5.4"
    ports:
          - "5432:5432"
    env_file:
      - ./env.db
    volumes:
      - "postgres-data:/var/lib/postgresql/data:rw"
    restart: always
    networks:
      - gms

volumes:
  postgres-data:

networks:
  gms:
